[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300

[environments]
  [environments.production]
    APP_ENV = "production"
    NODE_ENV = "production"
  
  [environments.preview]
    APP_ENV = "preview"
    NODE_ENV = "production"